<a href="https://colab.research.google.com/github/likhith040/likhithsrao/blob/main/numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

data = {
    "Name": ["Ram", "Shyam", "Ram", "Sita", None,"Shyam","Shyam","Shyam","Ram"],
    "Age": [25, np.nan, 25, 30, 22,13,17,18,19],
    "City": ["Mumbai", "mumbai", "Mumbai", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi"]
}
print(data)
df= pd.DataFrame(data)
df

{'Name': ['Ram', 'Shyam', 'Ram', 'Sita', None, 'Shyam', 'Shyam', 'Shyam', 'Ram'], 'Age': [25, nan, 25, 30, 22, 13, 17, 18, 19], 'City': ['Mumbai', 'mumbai', 'Mumbai', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi']}

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [ ]:
# First few rows
df.head()

# Data info
df.info()

# Summary statistics
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      float64
 2   City    9 non-null      object
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes

            Age
count   8.00000
mean   21.12500
std     5.43632
min    13.00000
25%    17.75000
50%    20.50000
75%    25.00000
max    30.00000

In [ ]:
df.isnull()
df.isnull().sum()

Name    1
Age     1
City    0
dtype: int64

In [ ]:
df_drop=df.dropna()
df_drop

    Name   Age    City
0    Ram  25.0  Mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [ ]:


df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])
df

    Name     Age    City
0    Ram  25.000  Mumbai
1  Shyam  21.125  mumbai
2    Ram  25.000  Mumbai
3   Sita  30.000   Delhi
4  Shyam  22.000   Delhi
5  Shyam  13.000   Delhi
6  Shyam  17.000   Delhi
7  Shyam  18.000   Delhi
8    Ram  19.000   Delhi

In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame({
    "Age": [20, np.nan, 25, 30,20],
    "Salary": [20000, 25000, np.nan, 40000,20000],
    "City": ["Mumbai", "Delhi", "Pune", "Mumbai","Mumbai"]
})

df

    Age   Salary    City
0  20.0  20000.0  Mumbai
1   NaN  25000.0   Delhi
2  25.0      NaN    Pune
3  30.0  40000.0  Mumbai
4  20.0  20000.0  Mumbai

In [ ]:
# Fill multiple columns with mean

df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())

df

     Age   Salary    City
0  20.00  20000.0  Mumbai
1  23.75  25000.0   Delhi
2  25.00  26250.0    Pune
3  30.00  40000.0  Mumbai
4  20.00  20000.0  Mumbai

In [ ]:
# Increase values by 10%
df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)

df

      Age   Salary    City
0  22.000  22000.0  Mumbai
1  26.125  27500.0   Delhi
2  27.500  28875.0    Pune
3  33.000  44000.0  Mumbai
4  22.000  22000.0  Mumbai

In [ ]:
# Replace specific values

df[["City"]] = df[["City"]].replace("Mumbai", "MUMBAI")

df

      Age   Salary    City
0  22.000  22000.0  MUMBAI
1  26.125  27500.0   Delhi
2  27.500  28875.0    Pune
3  33.000  44000.0  MUMBAI
4  22.000  22000.0  MUMBAI

In [ ]:
df_encoded = pd.get_dummies(df, columns=["City"])
df_encoded

      Age   Salary  City_Delhi  City_MUMBAI  City_Pune
0  22.000  22000.0       False         True      False
1  26.125  27500.0        True        False      False
2  27.500  28875.0       False        False       True
3  33.000  44000.0       False         True      False
4  22.000  22000.0       False         True      False

In [ ]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()

df2

      Age   Salary    City
0  22.000  22000.0  MUMBAI
1  26.125  27500.0   DELHI
2  27.500  28875.0    PUNE
3  33.000  44000.0  MUMBAI
4  22.000  22000.0  MUMBAI

In [ ]:
df_no_dup = df.drop_duplicates()
df_no_dup

      Age   Salary    City
0  22.000  22000.0  MUMBAI
1  26.125  27500.0   DELHI
2  27.500  28875.0    PUNE
3  33.000  44000.0  MUMBAI

In [ ]:
df_no_dup = df.drop_duplicates()
df_no_dup

      Age   Salary    City
0  22.000  22000.0  MUMBAI
1  26.125  27500.0   DELHI
2  27.500  28875.0    PUNE
3  33.000  44000.0  MUMBAI